# Generated by Django 5.0.7 on 2024-07-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_remove_listing_is_active_listing_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
