# Generated by Django 5.0.7 on 2024-07-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_rename_owner_listing_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
