# Generated by Django 5.0.7 on 2024-07-18 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_deadline',
            field=models.DateField(default=datetime.datetime(2024, 7, 19, 23, 43, 34, 6193, tzinfo=datetime.timezone.utc)),
        ),
    ]
