# Generated by Django 5.0.7 on 2024-07-19 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_booking_cancellation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_deadline',
            field=models.DateField(default=datetime.datetime(2024, 7, 20, 0, 0, 56, 291005, tzinfo=datetime.timezone.utc)),
        ),
    ]
